NTTShopAdmin/Entities/Editar.cs
using NTTShopAdmin.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NTTShopAdmin.Models
{
    public class Editar :IValidatableObject
    {
        public Producto producto { get; set; }
        public DesProducto desProducto { get; set; }
        public ProductoRate productoRate { get; set; }

        public void IdProducto()
        {
            productoRate.idProducto = producto.idProducto;
            desProducto.idProducto = producto.idProducto;
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var result= new List<ValidationResult>();
            if(desProducto != null)
            {
               
                    if (string.IsNullOrEmpty(desProducto.nombre))
                    {
                        result.Add(new ValidationResult("Es necesario introducir un nombre de producto.", new[] { nameof(desProducto.nombre) }));
                    }
                    if (string.IsNullOrEmpty(desProducto.descripcion))
                    {
                        result.Add(new ValidationResult("Es necesario introducir una descripción del producto.", new[] { nameof(desProducto.descripcion) }));
                    }
            }
            if(productoRate != null)
            {
                if (productoRate.idRate == 0) 
                {
                        result.Add(new ValidationResult("Es necesario escoger un tipo de tarifa.", new[] { nameof(productoRate.idRate) }));
                }
                if (productoRate.precio == 0 || productoRate.precio < 0)
                {
                        result.Add(new ValidationResult("Precio inválido.", new[] { nameof(productoRate.precio) }));
                }
            }
            if(producto != null)
            {
                if (string.IsNullOrEmpty(producto.descripcion[0].nombre))
                {
                    result.Add(new ValidationResult("Es necesario introducir un nombre de producto.", new[] { nameof(desProducto.nombre) }));
                }
                if (string.IsNullOrEmpty(producto.descripcion[0].descripcion))
                {
                    result.Add(new ValidationResult("Es necesario introducir una descripción del producto.", new[] { nameof(desProducto.descripcion) }));
                }
                if (producto.rate[0].precio == 0 || producto.rate[0].precio < 0)
                {
                    result.Add(new ValidationResult("Precio inválido.", new[] { nameof(productoRate.precio) }));
                }
            }
            return result;
        }
    }
}

NTTShopAdmin/Entities/Idioma.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTTShopAdmin.Models
{
    public class Idioma
    {
        public int idIdioma { get; set; }
        
        [Required(ErrorMessage = "Es necesario introducir una descripción de Idioma.")]
        [RegularExpression(@"^[^\d]+$", ErrorMessage = "El campo DESCRIPCIÓN no puede contener números.")]
        public string descripcion { get; set; }
       
        [Required(ErrorMessage = "Es necesario introducir una ISO.")]
        [RegularExpression(@"^[^\d]+$", ErrorMessage = "El campo ISO no puede contener números.")]
        public string iso { get; set; }

        //public SelectList idiomas { get; set; }
    }
}

NTTShopAdmin/Controllers/IdiomasController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NTTShopAdmin.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace NTTShopAdmin.Controllers
{
    public class IdiomasController : Controller
    {

        private string generalUrl = "http://localhost:5000/api/";

        // GET: Idiomas
        public ActionResult Index(int? pageSize, int? page)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }



            var listadoIdiomas = getAllIdiomas();
            pageSize = (pageSize ?? 5);

            //Al igual que aquí, si el número de página es nulo, se indicará en la página 1
            page = (page ?? 1);

            ViewBag.PageSize = pageSize;

            return View(listadoIdiomas.ToPagedList(page.Value, pageSize.Value));
        }

        [HttpGet]
        public ActionResult Editar(int? idIdioma)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (idIdioma == null)
            {
                return View("Error");
            }
            else
            {
                var idioma = getIdioma(idIdioma);
                return View(idioma);
            }
            

        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Editar(Idioma idioma)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            string error = "";
            if (ModelState.IsValid)
            {
                bool correcto = ActIdioma(idioma, out error);
                if (correcto)
                {
                    ViewData["correcto"] = true;
                    return View();
                }
                else
                {
                    ViewData["error"] = error;
                    return View();
                }
            }
            return View(idioma);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Crear (Idioma idioma)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            string mensaje = "";
            if (ModelState.IsValid)
            {
                if (InsertarIdioma(idioma, out mensaje))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["error"] = mensaje;
                    return View(idioma);
                }
            }
            else
            {
                return View(idioma);
            }
        }

        [HttpGet]
        public ViewResult Detalles(int ? idIdioma)
        {
            var idioma = getIdioma(idIdioma);
            var pedidos = ListaProductoIdioma(idioma.iso);
            var usuarios = ListadoUsuario();
            var admins = ListadoAdmin();
            
            List<Usuario> usuariosIdioma = new List<Usuario>();
            foreach (var usuario in usuarios)
            {
                if(usuario.IsoIdioma == idioma.iso)
                {
                    usuariosIdioma.Add(usuario);
                }
            }

            List<ManagementUser> lista = new List<ManagementUser>();
            foreach(var admin in admins)
            {
                if(admin.isoIdioma == idioma.iso)
                {
                    lista.Add(admin);
                }
            }

            if(usuariosIdioma.Count>0 || pedidos.Count > 0 || lista.Count>0)
            {
                ViewBag.Eliminar = false;
            }
            else
            {
                ViewBag.Eliminar = true;
            }
            
            ViewBag.UsuariosIdioma = usuariosIdioma;
            return View(idioma);
        }

        [HttpGet]
        public ActionResult Eliminar(int idIdioma)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (EliminarIdioma(idIdioma))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("Error");
            }
        }

        private bool InsertarIdioma (Idioma idioma, out string error)
        {
            error = "";
            bool correcto = false;
            var idiomaData = new { idioma = idioma };
            string url = generalUrl + "Idioma/insertIdioma";
            string jsonDatos = JsonConvert.SerializeObject(idiomaData);
            try
            {
                var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                httpRequest.Method = "POST";
                httpRequest.ContentType = "application/json";
                httpRequest.Accept = "application/json";

                using (var streamWriter = new StreamWriter(httpRequest.GetRequestStream()))
                {

                    streamWriter.Write(jsonDatos);
                }

                var httpResponse = (HttpWebResponse)httpRequest.GetResponse();
                HttpStatusCode httpStatus = httpResponse.StatusCode;

                if (httpStatus == HttpStatusCode.OK)
                {
                    correcto = true;
                }
                else
                {
                    using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                    {
                        string errorMensaje = streamReader.ReadToEnd();
                        Console.WriteLine(errorMensaje);
                    }
                }
            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("400")) //BadRequest
                {
                    error = "Algún dato introducido es inválido.";

                }
                else if (ex.Message.Contains("404")) //NotFound
                {

                    error = "Algún dato introducido ya existe.";
                }
            }
            return correcto;

        }

        private bool ActIdioma (Idioma idioma, out string error)
        {
            
                error = "";
                bool correcto = false;
                var idiomaData = new { idioma = idioma };

                string jsonDatos = JsonConvert.SerializeObject(idiomaData);
                string url = generalUrl + "Idioma/updateIdioma";
                try
                {
                    var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                    httpRequest.Method = "PUT";
                    httpRequest.ContentType = "application/json";
                    httpRequest.Accept = "application/json";

                    using (var streamWriter = new StreamWriter(httpRequest.GetRequestStream()))
                    {

                        streamWriter.Write(jsonDatos);
                    }

                    var httpResponse = (HttpWebResponse)httpRequest.GetResponse();
                    HttpStatusCode httpStatus = httpResponse.StatusCode;

                    if (httpStatus == HttpStatusCode.OK)
                    {
                        correcto = true;
                    }

                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("404")) //BadRequest
                    {
                        error = "Algún dato no es válido o está repetido.";

                    }
                    else if (ex.Message.Contains("400")) //NotFound
                    {

                        error = "Algún dato está vacío o es nulo.";
                    }
                else
                {
                    error = "ERROR al ejecutar el procedimiento en la API.";
                }
                }
                return correcto;
            
        }

        private List<Idioma> getAllIdiomas()
        {
            List<Idioma> listaIdiomas = new List<Idioma>();
            try
            {
                string url = generalUrl + "Idioma/getAllIdiomas";
                var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                httpRequest.Method = "GET";

                var httpResponse = (HttpWebResponse)httpRequest.GetResponse();

                using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                {
                    var resultado = streamReader.ReadToEnd();
                    var json = JObject.Parse(resultado);
                    var pedidoArray = json["idiomaLista"].ToObject<JArray>();
                    listaIdiomas = pedidoArray.ToObject<List<Idioma>>();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return listaIdiomas;
        }

        private Idioma getIdioma(int? idIdioma)
        {
            Idioma idioma = new Idioma();
            string url = generalUrl + "Idioma/getIdioma/" + idIdioma;
            try
            {
                var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                httpRequest.Method = "GET";

                var httpResponse = (HttpWebResponse)httpRequest.GetResponse();

                using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))

NTTShopAdmin/Views/Idiomas/Crear.cshtml
@model NTTShopAdmin.Models.Idioma


<h2>Añadir un nuevo Idioma</h2>
@using (Html.BeginForm("Crear", "Idiomas", FormMethod.Post))
{
    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <div class="form-group" style="margin-top:15px;">
                        <label class="form-label fw-bold">ISO:</label>
                        @Html.TextBoxFor(a => a.iso, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.iso, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group" style="margin-top:15px;">
                        <label class="form-label fw-bold">Descripcion:</label>
                        @Html.TextBoxFor(a => a.descripcion, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="col-6">
                    <div class="form-group" style="margin-top:15px;" hidden>
                        <label class="form-label fw-bold">Descripcion:</label>
                        @Html.TextBoxFor(a => a.idIdioma, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.idIdioma, "", new { @class = "text-danger" })
                    </div>
                </div>*@
            </div>
        </div>
        <div class="col-12">
            @if (ViewData["error"] != null)
            {
                <p class="alert alert-danger" style="margin-top:10px;">@ViewData["error"]</p>
            }
            @if (ViewData["correcto"] is true)
            {
                <p class="alert alert-success" style="margin-top:10px;">Se han guardado correctamente los datos</p>
            }
        </div>
        <div class="col-6 d-grid gap-2 align-self-center" style="margin-top:45px;">
            <input type="submit" value="Guardar Datos" class="btn btn-outline-dark" />

        </div>
        <div class="col-6 d-grid gap-2 align-self-center" style="margin-top:45px;">
            @Html.ActionLink("Volver a la lista idiomas", "Index", "Idiomas", null, new { @class = "btn btn-outline-dark" })
        </div>
    </div>
}

NTTShopAdmin/Views/Idiomas/Detalles.cshtml
@model NTTShopAdmin.Models.Idioma
@{
    ViewBag.Title = "Detalles";

    var usuariosIdioma = ViewBag.UsuariosIdioma as List<NTTShopAdmin.Models.Usuario>;
}

<div class="row">
    <div class="col-6">
        <div class="row">
            <div class="col-12">
                <h2>Detalle Idioma @Html.DisplayFor(i => i.descripcion)</h2>
                <hr />
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-2">
                        <p class="fw-bold">IdIdioma:</p>
                    </div>
                    <div class="col-10">
                        @Html.DisplayFor(e => e.idIdioma)
                    </div>
                    <div class="col-2">
                        <p class="fw-bold">Descripción:</p>
                    </div>
                    <div class="col-10">
                        @Html.DisplayFor(e => e.descripcion)
                    </div>
                    <div class="col-2">
                        <p class="fw-bold">ISO:</p>
                    </div>
                    <div class="col-10">
                        @Html.DisplayFor(e => e.iso)
                    </div>
                </div>
            </div>
            <div class="col-12" style="margin-top:15px;">
                <div class="row">
                    <div class="col-12">
                        <h5>Eliminar Idioma:</h5>
                        <hr />
                    </div>
                    <div class="col-12">
                        @if (ViewBag.Eliminar is true)
                        {
                            <div class="col-12">
                                <div class="row">
                                    <div class="col-6 d-grid gap-2 align-self-center">
                                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal">
                                            Eliminar Idioma
                                        </button>
                                    </div>
                                    <div class="col-6 d-grid gap-2 align-self-center" >
                                        @Html.ActionLink("Volver a la lista de idiomas", "Index", "Idiomas", null, new { @class = "btn btn-outline-dark" })
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <p class="alert alert-danger">El Idioma @Model.descripcion NO se puede eliminar ya que está en USO.</p>
                            <div class="col-12 d-grid gap-2 align-self-center" style="margin-top:45px;">
                                @Html.ActionLink("Volver a la lista de idiomas", "Index", "Idiomas", null, new { @class = "btn btn-outline-dark" })
                            </div>
                        }
                    </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="col-6">
        <div class="row">
            <div class="col-12">
                <h2>Usuarios en @Model.descripcion</h2>
                <hr />
            </div>

            <div class="col-12">
                @if (usuariosIdioma.Count == 0)
                {
                    <p class="alert alert-danger">No hay ningún usuario que está utilizando el idioma <strong>@Model.descripcion</strong></p>
                }
                else
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>IdUsuario</th>
                                <th>NombreUsuario</th>
                                <th>Correo</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var usuario in usuariosIdioma)
                            {
                                <tr>
                                    <td>@usuario.IdUsuario</td>
                                    <td>@usuario.Inicio</td>
                                    <td>@usuario.Email</td>
                                    <td>@Html.ActionLink("Detalles", "Detalles", "Usuario", new { @idUsuario = usuario.IdUsuario }, new { @class = "bnt bnt-secondary" })</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                }

            </div>
        </div>
    </div>
    </div>
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="lblmodal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="lblmodal">Eliminar Iidoma</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>¿Estás seguro de eliminar el idioma <strong>@Model.descripcion</strong>?</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                @Html.ActionLink("Eliminar Idioma", "Eliminar", "Idiomas", new { @idIdioma = Model.idIdioma }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

NTTShopAdmin/Views/Idiomas/Editar.cshtml
@model NTTShopAdmin.Models.Idioma

<h2>Editar Idioma</h2>
@using (Html.BeginForm("Editar", "Idiomas", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2>Editar</h2>
    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <div class="form-group" style="margin-top:15px;">
                        <label class="form-label fw-bold">ISO:</label>
                        @Html.TextBoxFor(a => a.iso, new { @class = "form-control", @disabled = "disabled" })
                        @Html.ValidationMessageFor(a => a.iso)
                        @Html.HiddenFor(a => a.iso)
                    </div>
                </div>

                <div class="col-6">
                    <div class="form-group" style="margin-top:15px;">
                        <label class="form-label fw-bold">Descripcion:</label>
                        @Html.TextBoxFor(a => a.descripcion, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group" style="margin-top:15px;" hidden>
                        <label class="form-label fw-bold">Descripcion:</label>
                        @Html.TextBoxFor(a => a.idIdioma, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.idIdioma, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    <div class="col-12">
        @if (ViewData["error"] != null)
        {
            <p class="alert alert-danger" style="margin-top:10px;">@ViewData["error"]</p>
        }
        @if (ViewData["correcto"] is true)
        {
            <p class="alert alert-success" style="margin-top:10px;">Se han guardado correctamente los datos</p>
        }
    </div>
        <div class="col-6 d-grid gap-2 align-self-center" style="margin-top:45px;">
            <input type="submit" value="Guardar Datos" class="btn btn-outline-dark" />

        </div>
        <div class="col-6 d-grid gap-2 align-self-center" style="margin-top:45px;">
            @Html.ActionLink("Volver a la lista idiomas", "Index", "Idiomas", null, new { @class = "btn btn-outline-dark" })
        </div>
    </div>
}

NTTShopAdmin/Views/Idiomas/Index.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<NTTShopAdmin.Models.Idioma>
@{
    ViewBag.Title = "Index";
}

<h2>Lista de Idiomas</h2>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>ISO</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>

            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>


        </tr>
    </thead>
    <tbody>
        @foreach (var idioma in Model)
        {
            <tr>
                <td>@idioma.idIdioma</td>
                <td>@idioma.descripcion</td>
                <td>@idioma.iso</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>@Html.ActionLink("Detalles", "Detalles", "Idiomas", new { idIdioma = idioma.idIdioma }, new { @class = "btn btn-outline-secondary" })</td>
                <td>@Html.ActionLink("Editar", "Editar", "Idiomas", new { @idIdioma = idioma.idIdioma }, new { @class = "btn btn-outline-dark" })</td>
                @*<td>@Html.ActionLink("Eliminar", "Editar", "Idiomas", new { idIdioma = idioma.idIdioma }, new { @class = "btn btn-outline-danger" })</td>*@

            </tr>
        }

    </tbody>
</table>
@Html.ActionLink("Crear", "Crear", "Idiomas", null, new { @class = "btn btn-secondary" })

<div style="margin:0;">

    @Html.PagedListPager(Model, page => Url.Action("Index", "Idiomas", new { page, pageSize = ViewBag.PageSize }))
</div>