NTTShopAdmin/Entities/Editar.cs
using NTTShopAdmin.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NTTShopAdmin.Models
{
    public class Editar :IValidatableObject
    {
        public Producto producto { get; set; }
        public DesProducto desProducto { get; set; }
        public ProductoRate productoRate { get; set; }

        public void IdProducto()
        {
            productoRate.idProducto = producto.idProducto;
            desProducto.idProducto = producto.idProducto;
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var result= new List<ValidationResult>();
            if(desProducto != null)
            {
               
                    if (string.IsNullOrEmpty(desProducto.nombre))
                    {
                        result.Add(new ValidationResult("Es necesario introducir un nombre de producto.", new[] { nameof(desProducto.nombre) }));
                    }
                    if (string.IsNullOrEmpty(desProducto.descripcion))
                    {
                        result.Add(new ValidationResult("Es necesario introducir una descripción del producto.", new[] { nameof(desProducto.descripcion) }));
                    }
            }
            if(productoRate != null)
            {
                if (productoRate.idRate == 0) 
                {
                        result.Add(new ValidationResult("Es necesario escoger un tipo de tarifa.", new[] { nameof(productoRate.idRate) }));
                }
                if (productoRate.precio == 0 || productoRate.precio < 0)
                {
                        result.Add(new ValidationResult("Precio inválido.", new[] { nameof(productoRate.precio) }));
                }
            }
            if(producto != null)
            {
                if (string.IsNullOrEmpty(producto.descripcion[0].nombre))
                {
                    result.Add(new ValidationResult("Es necesario introducir un nombre de producto.", new[] { nameof(desProducto.nombre) }));
                }
                if (string.IsNullOrEmpty(producto.descripcion[0].descripcion))
                {
                    result.Add(new ValidationResult("Es necesario introducir una descripción del producto.", new[] { nameof(desProducto.descripcion) }));
                }
                if (producto.rate[0].precio == 0 || producto.rate[0].precio < 0)
                {
                    result.Add(new ValidationResult("Precio inválido.", new[] { nameof(productoRate.precio) }));
                }
            }
            return result;
        }
    }
}

NTTShopAdmin/Controllers/UsuarioAdminController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NTTShopAdmin.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace NTTShopAdmin.Controllers
{

    public class UsuarioAdminController : Controller
    {
        // GET: UsuarioAdmin

        //Mejoras 
        private string generalUrl = "http://localhost:5000/api/";

        private void DropDown()
        {
            var listaIdioma = GetAllIdioma();
            ViewBag.Idiomas = listaIdioma;
        }
        public ActionResult Index(int? pageSize, int? page)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (Session["IdUser"] != null)
            {
                var listadoAdmin = ListadoAdmin();
                //Si pageSize es nulo, por defecto se pondrá un valor de 10.
                pageSize = (pageSize ?? 10);

                //Al igual que aquí, si el número de página es nulo, se indicará en la página 1
                page = (page ?? 1);

                ViewBag.PageSize = pageSize;
                return View(listadoAdmin.ToPagedList(page.Value, pageSize.Value));
            }
            else
            {
                return View("~/Views/Login/Login.cshtml");
            }
        }

        [HttpGet]
        public ViewResult Crear()
        {
            DropDown();
            if (Session["IdUser"] != null)
            {
                return View();
            }
            else
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Crear(ManagementUser admin)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            string mensaje = "";
            DropDown();
            if (ModelState.IsValid)
            {
                if (InsertarAdmin(admin, out mensaje))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Mensaje=mensaje;
                    return View(admin);
                }
            }
            else
            {
                ViewBag.Mnesaje = "Error al añadir un nuevo ADMINISTRADOR";
                return View(admin);
            }
        }

        [HttpGet]
        public ViewResult Delete(int? id)
        {
            if (Session["IdUser"] != null)
            {
                if (id == null || GetAdmin(id) == null)
                {
                    return View("Error");
                }
                else
                {
                    var admin = GetAdmin(id);
                    return View(admin);
                }
            }
            else
            {
                return View("~/Views/Login/Login.cshtml");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (EliminarAdmin(id))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View("Error");
            }
        }

        [HttpGet]
        public ViewResult Editar(int? id)
        {
            if (Session["IdUser"] != null)
            {

                if (id == null || GetAdmin(id) == null)
                {
                    return View("Error");
                }
                else
                {
                    var edit = GetAdmin(id);
                    return View(edit);
                }
            }
            else
            {
                return View("~/Views/Login/Login.cshtml");
            }
        }

        [HttpGet]
        public ViewResult ActCorreo(int idAdmin)
        {
            var admin = GetAdmin(idAdmin);
            return View(admin);
        }


        [HttpPost]
        public ActionResult ActCorreo(ManagementUser objAdmin)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (ModelState.IsValid)
            {
                if (Cambiar(objAdmin.idUsuario, objAdmin.email))
                {
                    ViewBag.Correcto = true;
                }
                else
                {
                    ViewBag.Mensaje = "El corre introducido está registrado. Introduzca otro.";
                }
            }
            return View(objAdmin);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Editar(ManagementUser objAdmin)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            string error = "";
            if (ModelState.IsValid)
            {
                bool correcto = ActDatosAdmin(objAdmin, out error);
                if (correcto)
                {
                    ViewData["correcto"] = true;
                    return View();

                }
                else
                {
                    ViewData["mensaje"] = error;
                    return View();
                }
            }
            return View(objAdmin);
        }

        [HttpGet]
        public ViewResult CambiarContra (int idAdmin)
        {
            var admin = GetAdmin(idAdmin);
            return View(admin);
        }

        [HttpPost]
        public ActionResult CambiarContra(ManagementUser objAdmin)
        {
            if (Session["IdUser"] == null && Session["LoginUser"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (ModelState.IsValid)
            {
                if (CambiarContrasenya(objAdmin.idUsuario, objAdmin.contrasenya))
                {
                    ViewBag.Correcto = true;
                }
                else
                {
                    ViewBag.Mensaje = "La contraseña que has introducido es la misma que la anterior.";
                }
            }
            return View(objAdmin);
          
        }

        private bool Cambiar(int idUsuario, string correo)
        {
            bool correcto = false;
            try
            {

                string url = generalUrl + "GestionUsuario/updateEmail?idUsuario=" + idUsuario + "&correo=" + correo;

                var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                httpRequest.Method = "PUT";
                httpRequest.ContentType = "application/json";
                httpRequest.Accept = "application/json";

                var httpResponse = (HttpWebResponse)httpRequest.GetResponse();
                HttpStatusCode httpStatus = httpResponse.StatusCode;

                if (httpStatus == HttpStatusCode.OK)
                {
                    correcto = true;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                correcto = false;
            }
            return correcto;
        }
    

    private bool ActDatosAdmin(ManagementUser objAdmin, out string error)
        {
            error = "";
            bool correcto = false;
            var adminData = new { gesUsuario = objAdmin };

            string jsonDatos = JsonConvert.SerializeObject(adminData);
            string url = generalUrl + "GestionUsuario/updateGesUsuario";
            try
            {
                var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                httpRequest.Method = "PUT";
                httpRequest.ContentType = "application/json";
                httpRequest.Accept = "application/json";

                using (var streamWriter = new StreamWriter(httpRequest.GetRequestStream()))
                {

                    streamWriter.Write(jsonDatos);
                }

                var httpResponse = (HttpWebResponse)httpRequest.GetResponse();
                HttpStatusCode httpStatus = httpResponse.StatusCode;

                if (httpStatus == HttpStatusCode.OK)
                {
                    correcto = true;
                }

            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("400")) //BadRequest
                {
                    error = "Algún dato está vacío o es nulo.";

                }
                else if (ex.Message.Contains("404")) //NotFound
                {

                    error = "Algún dato introducido ya existe o es inválido.";
                }
            }
            return correcto;
        }

        private bool EliminarAdmin(int id)
        {
            bool correcto = false;
            string url = generalUrl + "GestionUsuario/deleteGesUsuario/" + id;
            try
            {
                var httpRequest = (HttpWebRequest)WebRequest.Create(url);
                httpRequest.Method = "DELETE";
                httpRequest.ContentType = "application/json";
                httpRequest.Accept = "application/json";

                var httpResponse = (HttpWebResponse)httpRequest.GetResponse();
                HttpStatusCode httpStatus = httpResponse.StatusCode;

                if (httpStatus == HttpStatusCode.OK)
                {
                    correcto = true;
                }
                else
                {
                    using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))

NTTShopAdmin/Views/UsuarioAdmin/ActCorreo.cshtml
@{
    ViewBag.Title = "ActCorreo";
}
@model NTTShopAdmin.Models.ManagementUser


@using (Html.BeginForm("ActCorreo", "UsuarioAdmin", FormMethod.Post))
{
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h2 class="text-center">Actualizar correo</h2>
            <hr />
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @if (@ViewBag.Message != null)
            {
                <div style="border: 1px solid red">
                    @ViewBag.Message
                </div>
            }
            <div class="form-group">
                <label class="form-label fw-bold">Usuario:</label> <br />
                @Html.TextBoxFor(a => a.inicio, new { @class = "form-control", @disabled = "disabled" })
                @Html.ValidationMessageFor(a => a.inicio)
                @Html.HiddenFor(a => a.inicio)
            </div>
            @Html.HiddenFor(a => a.idUsuario)
            @Html.HiddenFor(a => a.apellido2)
            @Html.HiddenFor(a => a.apellido1)
            @Html.HiddenFor(a => a.contrasenya)
            @Html.HiddenFor(a => a.isoIdioma)
            @Html.HiddenFor(a => a.nombre)



            <div class="form-group">
                <label class="form-label fw-bold">Nuevo correo:</label><br />
                @Html.TextBoxFor(a => a.email, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.email, "", new { @class = "text-danger" })
            </div>
            @if (ViewData["errorMensaje"] != null)
            {
                <p class="alert alert-danger" style="margin-top:10px;">@ViewData["errorMensaje"]</p>
            }
            <div class="col-12 d-grid" style="margin-top:10px;">
                <input type="submit" value="Actualizar Correo" class="btn btn-outline-secondary" />
            </div>
            <div class="col-12 d-grid" style="margin-top:10px;">
                @Html.ActionLink("Volver a Editar Administrador", "Editar", "UsuarioAdmin", new { id = Model.idUsuario }, new { @class = "btn btn-outline-secondary" })
            </div>
            @if (ViewBag.Correcto is true)
            {
                <p class="alert alert-success">Correo Actualizado</p>
            }
            @if (ViewBag.Mensaje != null)
            {
                <p class="alert alert-danger">@ViewBag.Mensaje</p>
            }
        </div>


    </div>
}

NTTShopAdmin/Views/UsuarioAdmin/CambiarContra.cshtml
@model NTTShopAdmin.Models.ManagementUser
@{
    ViewBag.Title = "CambiarContra";
}

<h2>Cambiar Contraseña</h2>


@using (Html.BeginForm("CambiarContra", "UsuarioAdmin", FormMethod.Post))
{
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h2 class="text-center">Cambiar Contraseña</h2>
            <hr />
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @if (@ViewBag.Message != null)
            {
                <div style="border: 1px solid red">
                    @ViewBag.Message
                </div>
            }
            <div class="form-group">
                <label class="form-label fw-bold">Usuario:</label> <br />
                @Html.TextBoxFor(a => a.inicio, new { @class = "form-control", @disabled = "disabled" })
                @Html.ValidationMessageFor(a => a.inicio)
                @Html.HiddenFor(a => a.inicio)
            </div>
            <div class="form-group">
                <label class="form-label fw-bold">Contraseña:</label><br />
                @Html.PasswordFor(a => a.contrasenya, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.contrasenya, "", new {@class="text-danger"})
            </div>
            @if (ViewData["errorMensaje"] != null)
            {
                <p class="alert alert-danger" style="margin-top:10px;">@ViewData["errorMensaje"]</p>
            }
            <div class="col-12 d-grid" style="margin-top:10px;">
                <input type="submit" value="Actualizar Contraseña" class="btn btn-outline-secondary" />
            </div>
            <div class="col-12 d-grid" style="margin-top:10px;">
                @Html.ActionLink("Volver a Editar Administrador", "Editar", "UsuarioAdmin", new { @id = Model.idUsuario }, new { @class = "btn btn-outline-secondary" })
            </div>
            @if (ViewBag.Correcto is true)
            {
                <p class="alert alert-success">Contraseña Actualizada</p>
            }
            @if (ViewBag.Mensaje != null)
            {
                <p class="alert alert-danger">@ViewBag.Mensaje</p>
            }
        </div>
      

    </div>
    @*<div class="form-group" hidden>
        <label class="form-label fw-bold">idUsuario:</label> <br />
        @Html.TextBoxFor(a => a.idUsuario, new { @class = "form-control" })
    </div>
    <div class="form-group" hidden>
        <label class="form-label fw-bold">nombre:</label> <br />
        @Html.TextBoxFor(a => a.nombre, new { @class = "form-control" })
    </div>
    <div class="form-group" hidden>
        <label class="form-label fw-bold">idUsuario:</label> <br />
        @Html.TextBoxFor(a => a.apellido2, new { @class = "form-control" })
    </div>
    <div class="form-group" hidden>
        <label class="form-label fw-bold">idUsuario:</label> <br />
        @Html.TextBoxFor(a => a.apellido1, new { @class = "form-control" })
    </div>
    <div class="form-group" hidden>
        <label class="form-label fw-bold">e:</label> <br />
        @Html.TextBoxFor(a => a.email, new { @class = "form-control" })
    </div>
    <div class="form-group" hidden>
        <label class="form-label fw-bold">idUsuario:</label> <br />
        @Html.TextBoxFor(a => a.isoIdioma, new { @class = "form-control" })
    </div>*@
    @*<legend>Introduzca las credenciales del usuario administrador</legend>*@

  

}

NTTShopAdmin/Views/UsuarioAdmin/Crear.cshtml
@model NTTShopAdmin.Models.ManagementUser

@{
    ViewBag.Title = "Crear";
    var Mensaje = ViewBag.Mensaje;
}

@using (Html.BeginForm("Crear", "UsuarioAdmin", FormMethod.Post))
{
    <h2>Crear un nuevo Administrador</h2>
    <div class="row">
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Nombre:</label>
                @Html.TextBoxFor(a => a.nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <div class="col-6">
                    <div class="form-group" style="margin-top:15px;">
                        <label class="form-label fw-bold">Apellido 1:</label>
                        @Html.TextBoxFor(a => a.apellido1, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.apellido1, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group" style="margin-top:15px;">
                        <label class="form-label fw-bold">Apellido 2:</label>
                        @Html.TextBoxFor(a => a.apellido2, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.apellido2, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Correo:</label>
                @Html.TextBoxFor(a => a.email, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Nombre Usuario:</label>
                @Html.TextBoxFor(a => a.inicio, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.inicio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Contraseña:</label>
                @Html.TextBoxFor(a => a.contrasenya, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.contrasenya, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <div class="row" style=" margin-top:50px;">
                    <div class="col-2">
                        <div class="form-label  fw-bold">Idioma:</div>
                    </div>
                    <div class="col-5" @*style="padding-left:15px;"*@>
                        @Html.DropDownListFor(a => a.isoIdioma, new SelectList(ViewBag.Idiomas, "iso", "descripcion"))
                    </div>
                </div>
            </div>
        </div>
            @if (ViewBag.Mensaje != null)
            {
                <div class="col-12 d-grid gap-2 align-self-center" style="margin-top:45px;">
                    <p class="alert alert-danger" style="margin-top:10px;"> Errror al añadir el administrador: @Mensaje</p>
                </div>
            }
       
        <div class="col-6 d-grid gap-2 align-self-center" style="margin-top:45px;">
            <input type="submit" value="Añadir Administrador" class="btn btn-outline-dark" />
        </div>
        <div class="col-6 d-grid gap-2 align-self-center" style="margin-top:45px;">
            @Html.ActionLink("Volver a la lista productos", "Index", "UsuarioAdmin", null, new { @class = "btn btn-outline-secondary" })
        </div>
    </div>
}

NTTShopAdmin/Views/UsuarioAdmin/Delete.cshtml
@model NTTShopAdmin.Models.ManagementUser
@{
    ViewBag.Title = "Delete";
}

@using (Html.BeginForm("Delete", "UsuarioAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2>Eliminar Usuario Admin</h2>
    <div class="row">
        <div class="col-12">
            <h4>¿Estás seguro de eliminar el usuario seleccionado?</h4>
            <hr />
        </div>
        <div class="col-2 fw-bold">
            @Html.DisplayNameFor(model => model.idUsuario):
        </div>
        <div class="col-10">
            @Html.DisplayFor(model => model.idUsuario)
        </div>
        <div class="col-2 fw-bold">
            Nombre Usuario:
        </div>
        <div class="col-10 ">
            @Html.DisplayFor(model => model.inicio)
        </div>
        <div class="col-2 fw-bold">
            Nombre:
        </div>
        <div class="col-10">
            @Html.DisplayFor(model => model.nombre)
        </div>
        <div class="col-2 fw-bold">
            Apellidos:
        </div>
        <div class="col-10">
            @Html.DisplayFor(model => model.apellido1) @Html.DisplayFor(model => model.apellido2)
        </div>
        <div class="col-2 fw-bold">
            Email:
        </div>
        <div class="col-10">
            @Html.DisplayFor(model => model.email)
        </div>
        <div class="col-4 d-grid gap-2 align-self-center" style="margin-top:45px;">
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal">
                Eliminar Administrador
            </button>
        </div>
        <div class="col-4 d-grid gap-2 align-self-center" style="margin-top:45px;">
            @Html.ActionLink("Volver a la lista de Administradores", "Index", "UsuarioAdmin", null, new { @class = "btn btn-outline-secondary" })
        </div>

    </div>
    //MODAL
    <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="lblmodal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="lblmodal">Eliminar Administrador</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>¿Estás seguro de eliminar el Administrador <strong>@Model.nombre</strong>?</p> 
                                      
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrrar</button>
                    <input type="submit" class="btn btn-danger" value="Eliminar Administrador" />
                </div>
            </div>
        </div>
    </div>
    
 
}

NTTShopAdmin/Views/UsuarioAdmin/Editar.cshtml
@model NTTShopAdmin.Models.ManagementUser
@{
    ViewBag.Title = "Editar";
}

@using (Html.BeginForm("Editar", "UsuarioAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2>Editar</h2>
    <div class="row">
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Nombre:</label>
                @Html.TextBoxFor(a => a.nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Apellidos:</label>
                <div class="row">
                    <div class="col-6">
                        @Html.TextBoxFor(a => a.apellido1, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.apellido1, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-6">
                        @Html.TextBoxFor(a => a.apellido2, new { @class = "form-control" })

                        @Html.ValidationMessageFor(a => a.apellido2, "", new { @class = "text-danger" })
                    </div>
                </div>



            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Correo:</label>
                @Html.TextBoxFor(a => a.email, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-6">
            <div class="form-group" style="margin-top:15px;">
                <label class="form-label fw-bold">Usuario:</label>
                @Html.TextBoxFor(a => a.inicio, new { @class = "form-control", @disabled = "disabled" })
                @Html.ValidationMessageFor(a => a.inicio)
                @Html.HiddenFor(a => a.inicio)
            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;" hidden>
                <label class="form-label fw-bold">Correo:</label>
                @Html.TextBoxFor(a => a.idUsuario, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.idUsuario)
            </div>
        </div>
        <div class="col-6">
            <div class="form-group" style="margin-top:15px;" hidden>
                <label class="form-label fw-bold">Correo:</label>
                @Html.TextBoxFor(a => a.isoIdioma, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.isoIdioma)
            </div>
        </div>

        <div class="col-4 d-grid gap-2 align-self-center" style="margin-top:45px;">
            <input type="submit" value="Guardar Datos" class="btn btn-outline-dark" />

        </div>
        <div class="col-4 d-grid gap-2 align-self-center" style="margin-top:45px;">
            @Html.ActionLink("Cambiar Contraseña", "CambiarContra", "UsuarioAdmin", new { @idAdmin = Model.idUsuario }, new { @class = "btn btn-outline-dark" })
        </div>
        <div class="col-4 d-grid gap-2 align-self-center" style="margin-top:45px;">
            @Html.ActionLink("Actualizar correo", "ActCorreo", "UsuarioAdmin", new { @idAdmin = Model.idUsuario }, new { @class = "btn btn-outline-dark" })
        </div>
        <div class="col-12 d-grid gap-2" style="margin-top:25px;">
            @Html.ActionLink("Volver a la lista de administradores", "Index", "UsuarioAdmin", null, new { @class = "btn btn-secondary" })
        </div>
        <div class="col-12">
            @if (ViewData["error"] != null)
            {
                <p class="alert alert-danger" style="margin-top:10px;">@ViewData["error"]</p>
            }
            @if (ViewData["correcto"] is true)
            {
                <p class="alert alert-success" style="margin-top:10px;">Se han guardado correctamente los datos</p>
            }
        </div>

    </div>
}

NTTShopAdmin/Views/UsuarioAdmin/Index.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<NTTShopAdmin.Models.ManagementUser>
@{
    ViewBag.Title = "Index";
}

<h3>Listado Usuarios-Admin</h3>

<div class="rw">


    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Correo</th>
                <th>Nombre Usuario</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var admin in Model)
            {
                <tr>
                    <td>@admin.idUsuario</td>
                    <td>@admin.email</td>
                    <td>@admin.inicio</td>
                    <td>
                        <a>
                            @Html.ActionLink("Eliminar", "Delete", "UsuarioAdmin", new { @id = admin.idUsuario }, new { @class = "btn btn-outline-danger" })
                        </a>
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Editar", "UsuarioAdmin", new { @id = admin.idUsuario }, new { @class = "btn btn-outline-secondary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="col-5">
        @Html.ActionLink("Crear un nuevo Administrador", "Crear", "UsuarioAdmin", null, new { @class = "btn btn-outline-secondary" })
    </div>
    <div>

        @Html.PagedListPager(Model, page => Url.Action("Index", "UsuarioAdmin", new { page, pageSize = ViewBag.PageSize }))
    </div>
</div>